spring.application.name=publicStorage
spring.datasource.url=jdbc:postgresql://localhost:5432/publicstorage
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.client.registration.github.client-id=Ov23liE7wodcuCMuBjez
spring.security.oauth2.client.registration.github.client-secret=7f834b0d232a50649fba6ec823619a8ae2a6bc87
spring.security.oauth2.client.provider.github.user-name-attribute=login